# -*- coding: utf-8 -*-
"""Area of the Traingle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_SHKyE0zQw-222P5EdVnIjFaZRDLxFU9
"""

b=int(input("input the base value:"))
h=int(input("input the height value:"))
a=h*b*0.5
print("The area of the triangle is {:.2f}  ".format(a))