# -*- coding: utf-8 -*-
"""Flight Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16EVgl36Tabpck9fWGY6mD3oYkb5pwJ56
"""

airline_name=input("Enter Airline Name: ")
airline_number=int(input("Enter Airline Number: "))
airline_ticket=input("Enter Airline Ticket: ")
airline_country=input("Enter Airline Country: ")

print("********************Flight Details*********************")
print("Airline Name: {}".format(airline_name))
print("Airline Number: {}".format(airline_number))
print("Airline Ticket: {}".format(airline_ticket))
print("Airline Country: {}".format(airline_country))